language: scala
sudo: required
dist: trusty
before_install:
- curl https://raw.githubusercontent.com/scala-native/scala-native/21539aa97947f7/bin/travis_setup.sh | bash -x
- wget https://raw.githubusercontent.com/paulp/sbt-extras/3ba0e52f32d32c0454ec3a926caae2db0caaca12/sbt && chmod +x ./sbt
script:
- ./sbt exampleJVM/test exampleJS/test exampleNative/test exampleNative/nativeLink
- ./native/target/scala-2.11/scalaprops-cross-example-out
- ./native/target/scala-2.11/scalaprops-cross-example-test-out
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
